name: Deploy the website to Github Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Change if you need git info

      - name: Copy artifact to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USERNAME }}
          key: ${{ secrets.OVH_SERVER_KEY }}
          source: system/*
          target: /tmp
      - name: Move files to /usr/local/bin with sudo
        uses: appleboy/ssh-action@v1
        with:
         host: ${{ secrets.OVH_HOST }}
         username: ${{ secrets.OVH_USERNAME }}
         key: ${{ secrets.OVH_SERVER_KEY }}
         script: |
           sudo cp -r /tmp/system/* /